name: PR Slack Notifications

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
  pull_request_review:
    types: [submitted]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Created Notification
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review')
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "test-pr-notify",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🆕 New Pull Request Created!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR Title:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n*Repository:* `${{ github.repository }}`\n*Author:* `${{ github.event.pull_request.user.login }}`\n*Reviewers:* <@userID1> <@userID2>"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "${{ github.event.pull_request.user.avatar_url }}",
                    "alt_text": "Author Avatar"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Description:* \n${{ github.event.pull_request.body || 'No description provided.' }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "🔗 View Pull Request"
                      },
                      "url": "${{ github.event.pull_request.html_url }}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send PR Reviewed Notification
        if: github.event_name == 'pull_request_review' && github.event.action == 'submitted'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "test-pr-notify",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "📝 Pull Request Reviewed!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Reviewer:* `${{ github.event.review.user.login }}`\n*PR Title:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n*Review State:* `${{ github.event.review.state }}`"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "${{ github.event.review.user.avatar_url }}",
                    "alt_text": "Reviewer Avatar"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "🔗 View Pull Request"
                      },
                      "url": "${{ github.event.pull_request.html_url }}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send PR Merged Notification
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "test-pr-notify",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✅ Pull Request Merged!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR Title:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n*Merged by:* `${{ github.event.pull_request.merged_by.login }}`\n*Repository:* `${{ github.repository }}`"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "${{ github.event.pull_request.merged_by.avatar_url }}",
                    "alt_text": "Merger Avatar"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "🔗 View Pull Request"
                      },
                      "url": "${{ github.event.pull_request.html_url }}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
