name: PR Slack Notifications

on:
  pull_request:
    types: [opened, reopened, ready_for_review, review_requested, closed, edited]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Created Notification
        if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "test-pr-notify",
              "text": "🆕 New Pull Request Created!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🆕 New Pull Request Created!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR Title:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n*Repository:* `${{ github.repository }}`\n*Author:* `${{ github.event.pull_request.user.login }}`\n*Reviewers:* ${{ join(fromJson('["' + github.event.pull_request.requested_reviewers.*.login | join('","') + '"]'), ', ') || 'No reviewers assigned.' }}"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "${{ github.event.pull_request.user.avatar_url }}",
                    "alt_text": "Author Avatar"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Description:* \n${{ github.event.pull_request.body || 'No description provided.' }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "🔗 View Pull Request"
                      },
                      "url": "${{ github.event.pull_request.html_url }}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send PR Reviewed Notification
        if: github.event.action == 'edited' || github.event.action == 'review_requested'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "test-pr-notify",
              "text": "👀 PR Updated or Review Requested!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "👀 PR Updated or Review Requested!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR Title:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n*Repository:* `${{ github.repository }}`\n*Updated by:* `${{ github.actor }}`"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "🔍 View Pull Request"
                      },
                      "url": "${{ github.event.pull_request.html_url }}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send PR Merged Notification
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "test-pr-notify",
              "text": "🎉 Pull Request Merged!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🎉 Pull Request Merged!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR Title:* <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n*Merged by:* `${{ github.actor }}`"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "✅ View Merged PR"
                      },
                      "url": "${{ github.event.pull_request.html_url }}",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
